name: Graph Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: install gcc11
      uses: sudo apt install build-essential && sudo apt install -y gcc-11

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.1

    - name: Create default profile
      run: conan profile new default --detect

    - name: Update profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install dependencies
      run: conan install ${{github.workspace}} --install-folder=${{github.workspace}}/bin -s compiler=gcc -s compiler.version=11

    - name: Build
      run:  conan build ${{github.workspace}} --build-folder ${{github.workspace}}/bin

    - name: Run
      run: ${{github.workspace}}/bin/bin/graph_test