name: Graph Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Create default profile
      run: conan profile new default --detect

    - name: Update profile
      run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Install dependencies
      run: conan install ${{github.workspace}} --install-folder=${{github.workspace}}/bin

    - name: Configure CMake
      run: cmake -B ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cd ${{github.workspace}}/bin && conan build ${{github.workspace}} --build-folder ${{github.workspace}}/bin

    - name: Run
      run: ${{github.workspace}}/bin/graph_test